name: Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      # - name: Prettier check
      #   uses: creyD/prettier_action@v2.2
      #   with:
      #     dry: true
      #     prettier_options: --check **/*.ts

      - name: Use deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Run tests
        run: deno test
