name: Tests and examples
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Run tests
        run: deno test --doc

      - name: Linter
        run: deno lint

      - name: Formatter
        run: deno fmt --check

  examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Run examples
        run: deno task examples
