name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: denolib/setup-deno@v2
      with:
        deno-version: 1.0.0-rc1
    - run: deno run --allow-read --allow-run --allow-net specs/_run.ts
